### ISSUE TITLE
New clientId check using inconsistent array key

### ISSUE THREAD

**Issue by frankycastillo** [jofner/Twitch-SDK#10]
The new checks to enforce clientId in the construct is expecting 'clientId' as key instead of the previously used 'client_id'. This is then again checked on the configValidate() method but now looking for 'client_id' only to try to set the clientId on the setClientId() method from the 'clientId'

Please make the usage consistent to 'client_id' all around.

**Comment by jofner** [comment]
I hope it's fixed now. At this moment is hard to develop and test this for me, because actually i have no project with this library. So thanks for reporting.
