### ISSUE TITLE
Set Client-ID header for API calls

### ISSUE THREAD

**Issue by freaktechnik** [jofner/Twitch-SDK#8]
See https://blog.twitch.tv/client-id-required-for-kraken-api-calls-afbb8e95f843

**Comment by MikeMcMullan** [comment]
I have opened a pull request to fix this on the develop branch. https://github.com/jofner/Twitch-SDK/pull/9

**Comment by jofner** [comment]
Thanks you guys for your participation very much.

Client-ID supports added in commits 374d4f0 for develop and 473df94 for master.
